
CREATE DATABASE PROJECT


CREATE TABLE T_STORE(ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(70),
LOCATION VARCHAR(70));


CREATE TABLE T_CUSTOMER(ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(70),
EMAIL VARCHAR(50) UNIQUE
);

ALTER TABLE T_STORE ALTER COLUMN NAME VARCHAR(255);


ALTER TABLE T_CUSTOMER ALTER COLUMN NAME VARCHAR(255);


CREATE TABLE T_PRODUCT(ID INT PRIMARY KEY IDENTITY(1,1),

	NAME VARCHAR(255),
	PRICE DECIMAL(10,2),
	STORE_ID INT FOREIGN KEY REFERENCES T_STORE(ID)
);


CREATE TABLE T_ADDRESS(ID INT PRIMARY KEY IDENTITY(1, 1),
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	ZIPCODE INT,
	CUSTOMER_ID INT FOREIGN KEY REFERENCES T_CUSTOMER(ID)
);


CREATE TABLE T_ORDER(ID INT PRIMARY KEY IDENTITY(1,1),
	ORDER_DATE DATE,
	TOTAL_AMOUNT FLOAT,
	CUSTOMER_ID INT REFERENCES T_CUSTOMER(ID),
	DELIVERY_ADDRESS_ID INT REFERENCES T_ADDRESS(ID)
	
);


CREATE TABLE T_ORDERANDPRODUCT(ID INT PRIMARY KEY IDENTITY(1,1),
	ORDER_ID INT REFERENCES T_ORDER(ID),
	PRODUCT_ID INT REFERENCES T_PRODUCT(ID),
	QUANTITY INT
);

--DROP TABLE T_ORDERANDPRODUCT 
--ALTER TABLE T_ORDERANDPRODUCT ADD  QUANTITY INT;





SELECT * FROM T_STORE;

SELECT * FROM T_PRODUCT;
	
SELECT * FROM T_CUSTOMER;

SELECT * FROM T_ADDRESS; 

SELECT * FROM T_ORDER;

SELECT * FROM T_ORDERANDPRODUCT;

